[build.backend]
builder = "DOCKERFILE"
dockerfile = "./backend/Dockerfile"

[build.frontend]
builder = "DOCKERFILE"
dockerfile = "./frontend/Dockerfile"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10